# Generated by Django 5.0.6 on 2024-06-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_customer_cpf_alter_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
    ]
