# Generated by Django 5.0.6 on 2024-06-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_customer_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="pix_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boleto",
            name="qrcode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
